on:
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Key
        env:
          KEY: ${{ github.event.client_payload.key }}
          FIRSTNAME: ${{ github.event.client_payload.firstname }}
          LASTNAME: ${{ github.event.client_payload.lastname }}
        run: |
          echo $FIRSTNAME $LASTNAME
          ACCESSTOKENSECURE=${{ secrets.ACCESSTOKENSECURE }}
          curl -X POST -H "Authorization: Bearer $ACCESSTOKENSECURE" -H "Content-type: application/json" \
          -d '{
            "accountEnabled": true,
            "displayName": "Lkfen Doe",
            "mailNickname": "gwoe",
            "userPrincipalName": "jdfewee@kencamarador.com",
            "passwordProfile": {
              "forceChangePasswordNextSignIn": false,
              "password": "yourSeeeeeresword123"
            }
          }' \
          https://graph.microsoft.com/v1.0/users




        

