on:
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Execute script
        run: |
          ACCESSTOKENSECURE=${{ secrets.ACCESSTOKENSECURE }}
          $users = curl -s -X GET -H "Authorization: Bearer $ACCESSTOKENSECURE" -H "Content-type: application/json" https://graph.microsoft.com/v1.0/users
          echo "$users"



        

