on:
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          KEY: ${{ github.event.client_payload.key }}
          FIRSTNAME: ${{ github.event.client_payload.firstname }}
          LASTNAME: ${{ github.event.client_payload.lastname }}
          ACCESSTOKENSECURE: ${{ secrets.accessTokenSecure }}

      - name: Execute script
        run: |
          ACCESSTOKENSECURE = ${{ secrets.ACCESSTOKENSECURE }}
  
          $users = curl -s -X GET -H "Authorization: Bearer $ACCESSTOKENSECURE" -H "Content-type: application/json" https://graph.microsoft.com/v1.0/users
          echo $users



        

