on:
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Key
        env:
          KEY: ${{ github.event.client_payload.key }}
          FIRSTNAME: ${{ github.event.client_payload.firstname }}
          LASTNAME: ${{ github.event.client_payload.lastname }}
          ACCESSTOKENSECURE: ${{ secrets.accessTokenSecure }}
        run: echo $FIRSTNAME $LASTNAME

        $accessTokenSecure = ConvertTo-SecureString -String $env:ACCESSTOKENSECURE

        Connect-AzAccount -AccessToken $accessTokenSecure

        $UPN = "$FirstName.$LastName@arteria.ai"

        $PasswordProfile = New-Object -TypeName Microsoft.Open.AzureAD.Model.PasswordProfile
        $GeneratedPassword = New-AzureADUserPassword -Length 12 -IncludeLowercase -IncludeUppercase -IncludeNumbers -IncludeSpecialCharacters
        $PasswordProfile.Password = ConvertTo-SecureString -String $GeneratedPassword -AsPlainText -Force

        New-AzureADUser -DisplayName "$FIRSTNAME $LASTNAME" -PasswordProfile $PasswordProfile -UserPrincipalName $UPN -AccountEnabled $true


