on:
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Job Title
        run: |
          if [[ "${{ github.event.inputs.title }}" == "contractor" ]]; then
            echo "Job Title: Contractor"
            echo "JOBTITLE=contractor" >> $GITHUB_ENV
          fi
      - name: Account Provisioning - Developer
        env:
          KEY: ${{ github.event.client_payload.key }}
          FIRSTNAME: ${{ github.event.client_payload.firstname }}
          LASTNAME: ${{ github.event.client_payload.lastname }}
          JOBTITLE: ${{ github.event.client_payload.title }}
        run: |
          CLIENT_ID=${{ vars.CLIENT_ID }}
          CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
          
          TOKEN=$(curl -X POST \
          -H "Host: login.microsoftonline.com" \
          -H "Content-type: application/x-www-form-urlencoded" \
          https://login.microsoftonline.com/0496c0c5-5b34-4de0-a252-686f82ec384f/oauth2/v2.0/token \
          -d "client_id=$CLIENT_ID&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&client_secret=$CLIENT_SECRET&grant_type=client_credentials" \
          | jq -r .access_token)

          echo "Got the token"
          echo "$FIRSTNAME $LASTNAME to be created..."

          PASSWORD=$(openssl rand -base64 12)
          USERPRINCIPALNAME=$(echo "$FIRSTNAME.$LASTNAME@kencamarador.com" | tr '[:upper:]' '[:lower:]')
          DISPLAYNAME=$(echo "$FIRSTNAME $LASTNAME" | sed -E 's/\b([a-z])/\u\1/g')
          MAILNICKNAME=$(echo "$FIRSTNAME.$LASTNAME" | tr '[:upper:]' '[:lower:]')

          response=$(curl -X POST -H "Authorization: Bearer $TOKEN" -H "Content-type: application/json" \
          -d '{
            "accountEnabled": false,
            "displayName": "'"$DISPLAYNAME"'",
            "mailNickname": "'"$MAILNICKNAME"'",
            "jobTitle": "'"$JOBTITLE"'",
            "givenName": "'"$FIRSTNAME"'",
            "surName": "'"$LASTNAME"'",
            "mail": "'"$USERPRINCIPALNAME"'",
            "userPrincipalName": "'"$USERPRINCIPALNAME"'",
            "passwordProfile": {
              "forceChangePasswordNextSignIn": true,
              "password": "'"$PASSWORD"'"
            }
          }' \
          https://graph.microsoft.com/v1.0/users)

          object_id=$(echo "$response" | jq -r '.id')

          echo "Account created"
          echo "Account set to disabled"
          echo "Adding User to the default Azure AD Groups..."

          group_endpoints=(
            "https://graph.microsoft.com/v1.0/groups/dfd49c60-81f9-4995-8b36-fabbf8f70581/members/\$ref"
            "https://graph.microsoft.com/v1.0/groups/74e15387-a236-45ad-9b78-e18a778ba407/members/\$ref"

          )
          
          for endpoint in "${group_endpoints[@]}"; do
            curl -X POST -H "Authorization: Bearer $TOKEN" -H "Content-type: application/json" \
                -d "{
                      \"@odata.id\": \"https://graph.microsoft.com/v1.0/directoryObjects/$object_id\"
                    }" \
                "$endpoint"
          done

          echo "Azure AD Groups added succesfully"
          echo "Account provisioning completed, see details below:"

          user_created=$(echo "$response" | jq -r '.displayName')
          echo "User: $user_created"
          echo "User ID: $object_id"
          email_created=$(echo "$response" | jq -r '.userPrincipalName')
          echo "Email: $email_created"

