on: repository_dispatch  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      - env:
          KEY: ${{ github.event.client_payload.key }}
        run: echo $KEY