on:
  repository_dispatch:
    types: [issue.key]

jobs:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.issue.key }}
        run: echo $ISSUE.KEY
