on:
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: Set Job Title
        env:
          TITLE: ${{ github.event.client_payload.title }}
        run: |
          JOBTITLE="$TITLE"
          if [ "$JOBTITLE" == "Full Time" ]; then
            echo "::set-env name=JOBTITLE::"
          else
            echo "::set-env name=JOBTITLE::Contractor"
          fi
      - name: Echo Key
        env:
          KEY: ${{ github.event.client_payload.key }}
          FIRSTNAME: ${{ github.event.client_payload.firstname }}
          LASTNAME: ${{ github.event.client_payload.lastname }}
        run: |
          echo $JOBTITLE
          CLIENT_ID=${{ vars.CLIENT_ID }}
          CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
          
          TOKEN=$(curl -X POST \
          -H "Host: login.microsoftonline.com" \
          -H "Content-type: application/x-www-form-urlencoded" \
          https://login.microsoftonline.com/0496c0c5-5b34-4de0-a252-686f82ec384f/oauth2/v2.0/token \
          -d "client_id=$CLIENT_ID&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&client_secret=$CLIENT_SECRET&grant_type=client_credentials" \
          | jq -r .access_token)

          echo "Got the token"
          echo "User is "

          PASSWORD=$(openssl rand -base64 12)
          USERPRINCIPALNAME=$(echo "$FIRSTNAME.$LASTNAME@kencamarador.com" | tr '[:upper:]' '[:lower:]')
          DISPLAYNAME=$(echo "$FIRSTNAME $LASTNAME" | sed -E 's/\b([a-z])/\u\1/g')
          MAILNICKNAME=$(echo "$FIRSTNAME.$LASTNAME" | tr '[:upper:]' '[:lower:]')

          curl -X POST -H "Authorization: Bearer $TOKEN" -H "Content-type: application/json" \
          -d '{
            "accountEnabled": false,
            "displayName": "'"$DISPLAYNAME"'",
            "mailNickname": "'"$MAILNICKNAME"'",
            "jobTitle": "'"$JOBTITLE"'",
            "userPrincipalName": "'"$USERPRINCIPALNAME"'",
            "passwordProfile": {
              "forceChangePasswordNextSignIn": true,
              "password": "'"$PASSWORD"'"
            }
          }' \
          https://graph.microsoft.com/v1.0/users

