on:
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Key
        env:
          KEY: ${{ github.event.client_payload.key }}
          TITLE: ${{issue.summary.asJsonObject("title")}}
        run: echo $TITLE


