on:
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Key
        env:
          KEY: ${{ github.event.client_payload.key }}
          DESCRIPTION: ${{ github.event.client_payload.description }}
        run: echo $DESCRIPTION


